version: '3'

services:
  web:
    build: ./web
    ports:
      - "5000:5000"
    depends_on:
      - database

  database:
    image: postgres:10
    env_file:
      - .env
    volumes:
      - /var/lib/postgresql
    ports:
      - "5432:5432"
