version: '2'

services:
  web:
    build: ./web
    ports:
      - "5000:5000"
    depends_on:
      - postgres

  postgres:
    image: postgres:10
    env_file:
      - .env
    volumes:
      - /var/lib/postgresql
    expose:
      - "5432"
